### ISSUE TITLE
Create only one .ogv video with the results obtained in the simulation

### ISSUE THREAD

**Issue by josejuansanchez** [josejuansanchez/cr_mc_j2k#26]

**Comment by vicente-gonzalez-ruiz** [comment]
Hola!
¿Dónde está el vídeo?
Slds.

**Comment by josejuansanchez** [comment]
Hola!

Todavía no está subido, está pendiente de hacer.
He abierto esta *issue* para añadir la tarea a la lista de cosas pendientes.
Cuando cierre esta *issue* te tiene que llegar un aviso de que la tarea se ha completado.

Saludos,

JJ

**Comment by josejuansanchez** [comment]
Ya hay un primer resultado en este directorio:

`experiments/2015/2015_02_05_stockholm_layers-8_levels-2_precincts-128-64-32_blk-32_with_me_a_1_mode_auto/ogv`
